export { HancomDocsClient } from "./HancomDocsClient.js";
export {
  CapabilityUnavailableError,
  CdpProtocolError,
  EditorDiscoveryError,
  EditorPreconditionError,
  HancomDocsError,
  OperationTimeoutError,
  TargetDiscoveryError,
  UnsupportedOperationError
} from "./client/errors.js";
export type {
  CaretPosition,
  CaretTarget,
  ChromeTargetInfo,
  ConnectionOptions,
  DeleteTableRowRequest,
  DocumentBlock,
  DocumentReadCapabilities,
  DocumentSource,
  DocumentTableCell,
  DocumentTableRow,
  FillTableCellsRequest,
  FillTableCellsResult,
  HancomDocument,
  HancomDocumentMetadata,
  HwpJson20BinaryAsset,
  HwpJson20CharShape,
  HwpJson20ControlPayload,
  HwpJson20ControlToken,
  HwpJson20DocumentSnapshot,
  HwpJson20ParagraphRecord,
  HwpJson20ParaShape,
  HwpJson20StyleEntry,
  ImageBlock,
  ImageInsertResult,
  InsertImageRequest,
  InsertTableRequest,
  InsertTableResult,
  InsertTableRowRequest,
  PageNavigationResult,
  PageRange,
  ParagraphBlock,
  ParagraphFormatting,
  ParagraphFormattingResult,
  ParagraphLocator,
  ParagraphStyle,
  ParagraphStyleVariant,
  ReplaceAllRequest,
  ReplaceAllResult,
  SearchMatch,
  SearchOptions,
  SearchResult,
  SaveOptions,
  SaveResult,
  TableBlock,
  TableLocator,
  TableMutationResult,
  TableRowInsertPosition,
  TableSpec,
  TextRun,
  TextStyle
} from "./models/types.js";
export {
  flattenDocumentText,
  normalizeTableMatrix,
  resolveParagraphBlock,
  resolveTableBlock,
  summarizeParagraphFormatting,
  toDocumentBlocks
} from "./utils/document.js";
export { parseHwpJson20Document } from "./hancom/hwpJson20.js";
